export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_HAS_ERRORED = 'POSTS_HAS_ERRORED';
export const POSTS_ARE_LOADING = 'POSTS_ARE_LOADING';
export const POSTS_REORDER_SUCCESS = 'POSTS_REORDER_SUCCESS';
