// export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
// export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_HAS_ERRORED = 'POSTS_HAS_ERRORED';
export const POSTS_ARE_LOADING = 'POSTS_ARE_LOADING';
