export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
export const CATEGORIES_ARE_LOADING = 'CATEGORIES_ARE_LOADING';
